sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.2
node_js:
  - 4.1

before_install:
  - bundle install
  - npm install -g bower yamljs
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - bower install

before_script:
  # Convert show and workshop listings into web-usable JSON files
  - mkdir data
  - yaml2json _data/performances.yaml > data/performances.json
  - yaml2json _data/workshops.yaml > data/workshops.json

script:
  - JEKYLL_ENV=production bundle exec jekyll build

  - bundle exec htmlproofer --allow-hash-href --disable-external --check-html  _site
  - bundle exec scss-lint _assets/css
  - bundle exec yaml-lint _data
  - bundle exec yaml-lint _data _i18n .travis.yml _config.yml

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr / - ; fi`
  - docker build -t improvjaa/improfestival-2016:$TAG .
  - docker push improvjaa/improfestival-2016:$TAG
  - docker rmi improvjaa/improfestival-2016:$TAG

after_script:
  - docker logout

notifications:
  email:
    recipients:
      - ando@sqroot.eu
