
email: tilt@improfestival.ee
baseurl: ""
url: "http://localhost:4000"
languages: ["en", "et"]
exclude_from_localizations: ["assets"]
exclude: ["Gemfile", ".bundle", ".sass-cache", ".asset-cache", "Gemfile.lock", "Dockerfile", "README.md",".travis.yml", "vendor", "node_modules", "bower.json"]

markdown: kramdown
sass:
  sass_dir: _assets/css
gems: 
 - jekyll-assets
 - jekyll-multiple-languages-plugin

collections:
  - workshops
  - performances

assets:
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  cache_type: memory
  sources:  
    - "_assets/bower/font-awesome/fonts"
    - "_assets/bower/bootstrap-sass/assets/javascripts"
    - "_assets/bower/jquery/dist"
    - "_assets/bower"
  features:
   automatic_img_size: false

social:
  twitter: https://twitter.com/TILT_Improfest
  facebook: https://www.facebook.com/tilt.improfestival
  ical: https://improfestival.ee/#
  instagram: https://instagram.com/tilt_improfestival
  youtube: https://www.youtube.com/channel/UC7gOmWdcrS_He1XZnj1VjBQ
