
email: tilt@improfestival.ee
baseurl: ""
url: "http://localhost:4000"
languages: ["en", "et"]
exclude_from_localizations: ["img", "fonts", "css"]
exclude: ["Gemfile","Gemfile.lock", "Dockerfile", "README.md",".travis.yml", "vendor", "node_modules"]

markdown: kramdown

gems: 
 - jekyll-multiple-languages-plugin

social:
  twitter: https://twitter.com/TILT_Improfest
  facebook: https://www.facebook.com/tilt.improfestival