
email: tilt@improfestival.ee
baseurl: ""
url: "http://localhost:4000"
languages: ["en", "et"]
exclude_from_localizations: ["img", "fonts", "css"]
exclude: ["Gemfile", ".bundle", ".sass-cache", ".asset-cache", "Gemfile.lock", "Dockerfile", "README.md",".travis.yml", "vendor", "node_modules"]

markdown: kramdown

gems: 
 - jekyll-assets
 - jekyll-multiple-languages-plugin

assets:
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  cache_type: memory
  #assets:
  #  - "_assets/css"
  #  - "_assets/img"
  sources:  
    - "_assets/bower/font-awesome/fonts"

social:
  twitter: https://twitter.com/TILT_Improfest
  facebook: https://www.facebook.com/tilt.improfestival